#For A/B Deployments please ensure to set metadata.labels.service, metadata.labels.name,spec.selector.service to a value that can help you distinguish the pods
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-user