apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend-b
  name: frontend-b
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend-b
        api: external        
    spec:
      containers:
      - image: aizulhussin/udacity-frontend:v4
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

