apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-b
  name: frontend-b
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: frontend-b
  type: LoadBalancer    
