#For A/B Deployments please ensure to set labels.service, labels.name,spec.template.metadata.labels.service to a value that can help you distinguish the pods
#Please also ensure container image is set to the updated version / tag
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: aizulhussin/udacity-frontend:v3
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

