version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: aizulhussin/reverseproxy:v2 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: aizulhussin/udacity-restapi-user:v2
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: aizulhussin/udacity-restapi-feed:v2
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: aizulhussin/udacity-frontend:v2
